import Head from 'next/head';
import MainLayout from '../components/main-layout';
import ActivityMentorship from '../features/activity-mentorship';
import CollectionMentors from '../features/collection-mentors';
import ContactExpert from '../features/contact-expert';
import StoryMentor from "../features/story-mentors";
import Feedback from '../features/feedback';
import Banner from '../features/banner';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <Feedback />
        <ActivityMentorship />
        <CollectionMentors />
        <ContactExpert />
        <StoryMentor />
      </main>
    </>
  )
}
Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>;
};